### ISSUE TITLE
Create the net new deposits chart

### ISSUE THREAD

**Issue by amarante-codes** [msquaredsa-ds-dev/user-dash#4]

**Comment by amarante-codes** [comment]
use streamlit to deploy and deliver

**Comment by 0xBlackfish** [comment]
@amarante-codes - I've created a prototype version of this chart in Jupyter and created a rough idea of the schema required to simplify the data that sits underneath it.

Next step will be to create the semantic tables in GBQ and then write the Streamlit code to sit on top.
